### ISSUE TITLE
We have to choose where we will go!

### ISSUE THREAD

**Issue by marianashmul** [marianashmul/trip#2]

**Comment by uanchura** [comment]
Maybe Australia? I reckon it will be great!

**Comment by marianashmul** [comment]
No! I want to go to London! It is the best city in the world.

**Comment by uanchura** [comment]
In my opinion it's too depressive city. But, if be honest, I don't want to argue with you!!! Let it be London.

**Comment by marianashmul** [comment]
@uanchura Thanks. I hope you will like that
